---
- name: Restart NFS Worker
  ansible.builtin.systemd:
    name: nfs-server
    state: restarted
  become: true

- name: Reload Firewalld
  service:
    name: firewalld
    state: reloaded
  become: true
