---
- name: Apply common configuration
  hosts: all
  become: true
  roles:
    - common

- name : Configure Host Node
  hosts: host
  become: true
  roles:
    - rabbitmq
    - celery_host 

- name: Configure Worker Nodes
  hosts: workers
  become: true
  roles:
    - nfs
    - bio_tools 
    - celery_worker
